version: '3'
services:
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
    elasticsearch:
        image: "elasticsearch:5-alpine"
        ports:
            - "9200:9200"